version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
region = "us-east-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vbj40ve5bo3k"
capabilities = "CAPABILITY_IAM"
stack_name = "asset-driver-dev"
s3_prefix = "asset-driver-dev"
parameter_overrides = "VenueDriverFlyersSourceBucket=\"dev.asset-driver.venuedriver.com\" VenueDriverFlyersOutputBucket=\"dev.asset-driver.venuedriver.com\""

[staging.deploy.parameters]
stack_name = "asset-driver-staging"
s3_prefix = "asset-driver-staging"
parameter_overrides = "VenueDriverFlyersSourceBucket=\"staging-venuedriver-flyers\" VenueDriverFlyersOutputBucket=\"staging-assets.venuedriver.com\""

[production.deploy.parameters]
stack_name = "asset-driver-production"
s3_prefix = "asset-driver-production"
parameter_overrides = "VenueDriverFlyersSourceBucket=\"venuedriver_flyers\" VenueDriverFlyersOutputBucket=\"assets.venuedriver.com\""
