AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  asset-driver

Parameters:
  VenueDriverFlyersSourceBucket:
    Type: String
  VenueDriverFlyersOutputBucket:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        VENUE_DRIVER_FLYERS_SOURCE_BUCKET: !Ref 'VenueDriverFlyersSourceBucket'
        VENUE_DRIVER_FLYERS_OUTPUT_BUCKET: !Ref 'VenueDriverFlyersOutputBucket'

Resources:
  RunRules:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.run_rules
      Runtime: runtime
      Runtime: ruby2.5

Outputs:
  RunRules:
    Description: "Lambda function for running the asset processing rules."
    Value: !GetAtt RunRules.Arn
  VenueDriverFlyersSourceBucket:
    Description: "Source bucket to watch for Venue Driver flyer updates."
    Value: !Sub "${VenueDriverFlyersSourceBucket}"
  VenueDriverFlyersOutputBucket:
    Description: "Output bucket to for processed Venue Driver flyer images."
    Value: !Sub "${VenueDriverFlyersOutputBucket}"
