AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  asset-driver

Parameters:
  VenueDriverFlyersOutputRegion:
    Type: String
  VenueDriverFlyersOutputBucket:
    Type: String

Globals:
  Function:
    Runtime: ruby2.5
    Timeout: 900
    MemorySize: 512
    Environment:
      Variables:
        VENUE_DRIVER_FLYERS_OUTPUT_REGION: !Ref 'VenueDriverFlyersOutputRegion'
        VENUE_DRIVER_FLYERS_OUTPUT_BUCKET: !Ref 'VenueDriverFlyersOutputBucket'

Resources:
  RunRules:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.run_rules
  PreTrafficLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.pre_traffic_lambda_function
      Timeout: 900

Outputs:
  RunRules:
    Description: "Lambda function for running the asset processing rules."
    Value: !GetAtt RunRules.Arn
  VenueDriverFlyersOutputRegion:
    Description: "The AWS region of the output bucket."
    Value: !Sub "${VenueDriverFlyersOutputRegion}"
  VenueDriverFlyersOutputBucket:
    Description: "Output bucket to for processed Venue Driver flyer images."
    Value: !Sub "${VenueDriverFlyersOutputBucket}"
